releaseVersion=1.0.0-rc.1
releaseChannel=rc
androidApplicationId=com.xueqing.app
androidVersionCode=100001
androidVersionName=1.0.0-rc.1
windowsPackageName=Xueqing.Native
windowsPackageVersion=1.0.0.1
windowsArchitecture=x64
